/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherLessonsRouteImport } from './routes/teacher/lessons'
import { Route as TeacherStudentsRouteImport } from './routes/teacher/students'
import { Route as StudentRecordsIndexRouteImport } from './routes/student/records/index'
import { Route as StudentRecordsRecordIdRouteImport } from './routes/student/records/$recordId'
import { Route as StudentRecordsNewRouteImport } from './routes/student/records/new'
import { Route as TeacherRecordsIndexRouteImport } from './routes/teacher/records/index'
import { Route as TeacherRecordsRecordIdRouteImport } from './routes/teacher/records/$recordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentRecordsIndexRoute = StudentRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRecordsRecordIdRoute = StudentRecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRecordsNewRoute = StudentRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherRecordsIndexRoute = TeacherRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherRecordsRecordIdRoute = TeacherRecordsRecordIdRouteImport.update({
  id: '/records/$recordId',
  path: '/records/$recordId',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/records/$recordId': typeof StudentRecordsRecordIdRoute
  '/student/records/new': typeof StudentRecordsNewRoute
  '/teacher/records/$recordId': typeof TeacherRecordsRecordIdRoute
  '/student/records/': typeof StudentRecordsIndexRoute
  '/teacher/records/': typeof TeacherRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/records/$recordId': typeof StudentRecordsRecordIdRoute
  '/student/records/new': typeof StudentRecordsNewRoute
  '/teacher/records/$recordId': typeof TeacherRecordsRecordIdRoute
  '/student/records': typeof StudentRecordsIndexRoute
  '/teacher/records': typeof TeacherRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/teacher/lessons': typeof TeacherLessonsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/records/$recordId': typeof StudentRecordsRecordIdRoute
  '/student/records/new': typeof StudentRecordsNewRoute
  '/teacher/records/$recordId': typeof TeacherRecordsRecordIdRoute
  '/student/records/': typeof StudentRecordsIndexRoute
  '/teacher/records/': typeof TeacherRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/settings'
    | '/teacher/lessons'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/records/$recordId'
    | '/student/records/new'
    | '/teacher/records/$recordId'
    | '/student/records/'
    | '/teacher/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/settings'
    | '/teacher/lessons'
    | '/teacher/students'
    | '/student'
    | '/teacher'
    | '/student/records/$recordId'
    | '/student/records/new'
    | '/teacher/records/$recordId'
    | '/student/records'
    | '/teacher/records'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/settings'
    | '/teacher/lessons'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/records/$recordId'
    | '/student/records/new'
    | '/teacher/records/$recordId'
    | '/student/records/'
    | '/teacher/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/records/': {
      id: '/student/records/'
      path: '/records'
      fullPath: '/student/records/'
      preLoaderRoute: typeof StudentRecordsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/records/$recordId': {
      id: '/student/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/student/records/$recordId'
      preLoaderRoute: typeof StudentRecordsRecordIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/records/new': {
      id: '/student/records/new'
      path: '/records/new'
      fullPath: '/student/records/new'
      preLoaderRoute: typeof StudentRecordsNewRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/records/': {
      id: '/teacher/records/'
      path: '/records'
      fullPath: '/teacher/records/'
      preLoaderRoute: typeof TeacherRecordsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/records/$recordId': {
      id: '/teacher/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/teacher/records/$recordId'
      preLoaderRoute: typeof TeacherRecordsRecordIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface StudentRouteChildren {
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentRecordsRecordIdRoute: typeof StudentRecordsRecordIdRoute
  StudentRecordsNewRoute: typeof StudentRecordsNewRoute
  StudentRecordsIndexRoute: typeof StudentRecordsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentSettingsRoute: StudentSettingsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentRecordsRecordIdRoute: StudentRecordsRecordIdRoute,
  StudentRecordsNewRoute: StudentRecordsNewRoute,
  StudentRecordsIndexRoute: StudentRecordsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherLessonsRoute: typeof TeacherLessonsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherRecordsRecordIdRoute: typeof TeacherRecordsRecordIdRoute
  TeacherRecordsIndexRoute: typeof TeacherRecordsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherLessonsRoute: TeacherLessonsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherRecordsRecordIdRoute: TeacherRecordsRecordIdRoute,
  TeacherRecordsIndexRoute: TeacherRecordsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
